### ISSUE TITLE
What is '$r' in the synopsis?

### ISSUE THREAD

**Issue by szabgab** [powerman/perl-Mojolicious-Plugin-SecureCORS#1]
It would be nice if you could clarify what is `$r` in the synopsis and how do we get it?

**Comment by powerman** [comment]
It's well-known (for Mojolicious developers) name for routes object, used all of time in Mojo docs like:
- https://metacpan.org/pod/Mojolicious#routes
- https://metacpan.org/pod/distribution/Mojolicious/lib/Mojolicious/Guides/Routing.pod#Minimal-route
- https://metacpan.org/pod/distribution/Mojolicious/lib/Mojolicious/Guides/Cookbook.pod#Making-your-application-installable

Personally I don't think this have to be clarified in docs, but I'll accept PR with this change, so feel free to add what you think is missing/unclear in doc. :)
