### ISSUE TITLE
How to secure also post?

### ISSUE THREAD

**Issue by KarstenHalbleib** [powerman/perl-Mojolicious-Plugin-SecureCORS#7]
I thougt 'cors.origin' => '*' would send CORS Header for every method not only GET.
How can i secure also POST?

**Comment by powerman** [comment]
It works for any method you need. Personally I don't use Perl for years, but if you'll show me an example of your code which works for GET but not POST I'll try to help.

**Comment by KarstenHalbleib** [comment]
I found a workaround.
