### ISSUE TITLE
Mojolicious::Routes::Route::over is DEPRECATED in favor of Mojolicious::Routes::Route::requires

### ISSUE THREAD

**Issue by willsheppard** [powerman/perl-Mojolicious-Plugin-SecureCORS#8]
^ This is a warning seen with [Mojolicious 8.67](https://metacpan.org/changes/release/SRI/Mojolicious-8.67) which has deprecated some methods.

**Comment by powerman** [comment]
Thanks, but I'm not sure I'll have time for this any time soon.

Feel free to send a PR, if you like to.

**Comment by rabbiveesh** [comment]
I don't mind patching this. Do you want to only use the new methods, and bump up the required version, or to have a switch on version?

**Comment by powerman** [comment]
Released in 2.0.3. Thanks!
